version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: infra/docker/backend.Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      - QDRANT_HOST=qdrant

    depends_on:
      - qdrant

    volumes:
      - ../apps/backend:/app
      - ../base:/base

  frontend:
    build:
      context: ..
      dockerfile: infra/docker/frontend.Dockerfile

    ports:
      - "3000:3000"

  qdrant:
    image: qdrant/qdrant:latest

    container_name: qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - ./qdrant/storage:/qdrant/storage
      - ./qdrant/snapshots:/qdrant/snapshots